/*
 * Copyright 2021-2023 TTBT Enterprises LLC
 *
 * This file is part of c2FmZQ (https://c2FmZQ.org/).
 *
 * c2FmZQ is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * c2FmZQ is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * c2FmZQ. If not, see <https://www.gnu.org/licenses/>.
 */

/* jshint -W083 */
'use strict';

window.Lang = {
  init: () => {
    for (let lang of navigator.languages) {
      if (Lang.dict[lang]) {
        Lang.current = lang;
        break;
      }
    }
    if (window.localStorage) {
      const saved = window.localStorage.getItem('lang');
      if (saved && Lang.dict[saved] !== undefined) {
        Lang.current = saved;
      }
    }
  },

  current: 'en-US',

  languages: () => {
    let out = {};
    Object.keys(Lang.dict).forEach(x => {
      out[x] = Lang.dict[x].LANG;
    });
    return out;
  },

  text: (key, ...args) => {
    if (Lang.dict[Lang.current]) {
      let v = Lang.dict[Lang.current][key];
      if (v) return Lang.sub(v, args);
    }
    const lang = Lang.current.split('-')[0];
    if (Lang.dict[lang]) {
      let v = Lang.dict[lang][key];
      if (v) return Lang.sub(v, args);
    }
    console.log('Missing lang key', Lang.current, key);
    let v = Lang.dict.en[key];
    if (v) return Lang.sub(v, args);
    console.log('Missing lang key', 'en', key);
    return `::${key}:${args.join(' ')}::`;
  },

  sub: (s, args) => {
    for (let i = 0; i < args.length; i++) {
      s = s.replace(`$${i+1}`, args[i]);
    }
    return s;
  },

  dict: {
    'en': {
      'LANG': 'English',
      'language': 'Language',
      'login': 'Login',
      'logging-in': 'Logging in',
      'login-failed': 'Login failed',
      'register': 'Register',
      'create-account': 'Create Account',
      'creating-account': 'Creating Account',
      'create-account-failed': 'Account creation failed',
      'recover': 'Recover',
      'recover-account': 'Recover Account',
      'recovering-account': 'Recovering Account',
      'recover-account-failed': 'Account recovery failed',
      'enter-passphrase-text': '<p>Enter a passphrase to encrypt your app data.</p>',
      'reenter-passphrase-text': '<p>Unlock your app data</p>',
      'set-passphrase': 'Confirm',
      'setting-passphrase': 'Confirming',
      'skip-passphrase': 'Skip',
      'form-email': 'Email:',
      'form-password': 'Password:',
      'form-new-password': 'New password:',
      'form-confirm-password': 'Confirm password:',
      'form-backup-phrase': 'Backup phrase:',
      'form-backup-keys?': 'Backup keys?',
      'form-server': 'Server:',
      'server-placeholder': 'https://your-server-name/',
      'show': 'Show',
      'hide': 'Hide',
      'skip-passphrase-warning': '⚠️  Skipping the passphrase is less secure. Avoid using this option on a public or shared computer. Continue?',
      'no-key-backup-warning': '⚠️  Your secret key is NOT backed up. You will need a backup phrase next time you login.',
      'enter-backup-phrase': 'Enter backup phrase:',
      'account': '👤 ▼',
      'account-title': 'Account menu',
      'trash-title': 'Trash',
      'refresh-title': 'Refresh',
      'B': '$1 B',
      'KiB': '$1 KiB',
      'MiB': '$1 MiB',
      'GiB': '$1 GiB',
      'TiB': '$1 TiB',
      'MB': 'MB',
      'GB': 'GB',
      'TB': 'TB',
      'gallery': 'gallery',
      'trash': 'trash',
      'confirm': 'Confirm 👍',
      'cancel': 'Cancel 🚫',
      'canceled': 'Canceled',
      'cache-full': 'Cache is full',
      'data-saving-on': 'Data saving is enabled on device',
      'no-wifi': 'Waiting for wifi',
      'caching-disabled': 'Caching disabled',
      'ready': 'Ready',
      'drop-received': 'Processing new files',
      'upload:': 'Upload: $1',
      'collection': 'collection',
      'collection:': '$1',
      'collection-title': 'collection $1',
      'file-title': 'file $1',
      'list': '▤ ',
      'list-title': 'Display as list',
      'grid': '▦',
      'grid-title': 'Display as grid',
      'settings-title': 'Collection settings',
      'filename': 'Name',
      'filesize': 'Size',
      'creation-time': 'Creation time',
      'filetype': 'Type',
      'duration': 'Duration',
      'shared-with': 'Shared with $1',
      'empty': 'Empty',
      'name': 'Name:',
      'name:': 'Name: $1',
      'size:': 'Size: $1',
      'remove': 'Remove',
      'thumbnail-progress': 'Preparing: $1',
      'status:': 'Status: $1',
      'upload-progress': 'Upload: $1',
      'download-progress': 'Caching: $1',
      'add-button-title': 'Add items',
      'upload-files': 'Upload files',
      'upload': 'Upload',
      'uploading': 'Uploading',
      'select-upload': 'Select files to upload (or drag & drop files anywhere):',
      'profile': 'Profile',
      'required': 'required',
      'optional': 'optional',
      'enable-mfa?': 'Require MFA?',
      'enable-otp?': 'Enable OTP?',
      'enable-passkey?': 'Use resident keys\n(e.g. passkeys)?',
      'enter-code': 'Enter code',
      'updating': 'Applying changes',
      'error': 'Error',
      'new-pass-doesnt-match': 'New password doesn\'t match',
      'otp-code-required': 'OTP code required',
      'delete-warning': '<p>⚠️ If you delete your account, all your data will be permanently deleted.</p>',
      'delete-account': 'Delete my account',
      'confirm-delete-account': '⚠️ Are you sure you want to permanently delete your account?\nThe operation is not reversible.\n\nEnter your password:',
      'key-backup': 'Key backup',
      'enter-current-password': 'Enter your account password:',
      'key-backup-warning': '<p>⚠️ The backup phrase is your <b>unencrypted</b> secret key.</p><p>It is the most sensitive information in your account. It can be used to recover your account and your data if your secret key is not backed up on the server, or if you forget your password.</p><p>It can also be used to <b>TAKE OVER</b> your account.</p><p>It MUST be kept secret. Write it down on a piece of paper and store it in a safe.</p>',
      'show-backup-phrase': 'Show backup phrase',
      'hide-backup-phrase': 'Hide backup phrase',
      'checking-password': 'Checking password',
      'key-backup-warning2': '<p>Choose whether to keep an encrypted backup of your secret key on the server.<p><p>If you do NOT keep a backup, you will need to enter your backup phrase every time you login to your account.</p>',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'opt-keep-backup': 'Keep a backup on the server (RECOMMENDED)',
      'opt-dont-keep-backup': '⚠️ Do NOT keep a backup on the server',
      'prefs': 'Preferences',
      'choose-cache-pref': '<h1>Cache:</h1>',
      'opt-encrypted': 'Store encrypted files in a local browser cache. Whole collections can also be cached for offline access. The cache is cleared on logout or when another option is selected. (DEFAULT)',
      'opt-no-store': 'Disable caching. All files, including thumbnails, are fetched and decrypted each time they are accessed. This is the slowest option.',
      'opt-private': '⚠️ Use the default browser cache. Decrypted files are stored in the browser\'s cache. This is the option most likely to leak information.',
      'prefetch-all-thumbnails': 'Cache all thumbnails:',
      'use-mobile': 'Preload using mobile data:',
      'max-cache-size': 'Maximum size of cache (MiB):',
      'cache-usage': 'Current usage: $1 MiB',
      'choose-notifications-pref': '<h1>Notifications:</h1>',
      'opt-enable-notifications': 'Enable push notifications for important events like when friends add content to shared collections.',
      'saved': 'saved',
      'admin-console': 'Admin console',
      'email': 'Email',
      'locked': 'Locked',
      'approved': 'Approved',
      'admin': 'Admin',
      'quota': 'Quota',
      'open': 'Open',
      'download-doc': 'Download document',
      'copy-selected': 'Copy selected files',
      'move-selected': 'Move selected files',
      'edit': 'Edit',
      'edit:': 'Edit: $1',
      'select': 'Select',
      'unselect': 'Unselect',
      'unselect-all': 'Unselect all',
      'move-to-trash': 'Move to trash',
      'confirm-move-to-trash': 'Move to trash?',
      'move-to-gallery': 'Move to gallery',
      'confirm-move-to-gallery': 'Move to gallery?',
      'delete-perm': 'Delete permanently',
      'confirm-delete-perm': '⚠️ Delete permanently?',
      'use-as-cover': 'Use as cover',
      'move-to-gallery-only': 'Must move from trash to gallery',
      'moved-one-file': 'Moved 1 file',
      'moved-many-files': 'Moved $1 files',
      'copied-one-file': 'Copied 1 file',
      'copied-many-files': 'Copied $1 files',
      'deleted-one-file': 'Deleted 1 file',
      'deleted-many-files': 'Deleted $1 files',
      'confirm-leave': '⚠️ Are you sure you want to leave this collection?',
      'delete': 'Delete',
      'confirm-delete': '⚠️ Are you sure you want to delete this collection?',
      'properties': 'Properties',
      'properties:': 'Properties: $1',
      'offline-off': 'Available offline ☐',
      'offline-on': 'Available offline ☑',
      'create-collection': 'Create collection',
      'new-collection': 'NEW COLLECTION',
      'apply-changes': 'Apply changes',
      'no-changes': 'No changes',
      'shared': 'Shared:',
      'yes': 'Yes',
      'no': 'No',
      'next': 'Next',
      'previous': 'Previous',
      'close': 'Close window',
      'info': 'Show information',
      'expand': 'Show more details',
      'permissions': 'Permissions:',
      'perm-add': 'Add',
      'perm-share': 'Share',
      'perm-copy': 'Copy',
      'members': 'Members:',
      'contact-email': 'contact email',
      'add-member': 'Add',
      'none': 'none',
      'lock': 'Lock',
      'logout': 'Logout',
      'data-updated': 'Data updated',
      'network-error': 'offline?',
      'filter': 'filter',
      'notification-encrypted-title': 'Notifications ($1)',
      'notification-encrypted-body': 'New encrypted notifications waiting.',
      'new-user-title': 'New user: $1',
      'new-content-body': 'New files added.',
      'new-collection-body': 'Shared with you.',
      'new-members-body': 'New members joined.',
      'push-notifications-title': 'Push notifications',
      'push-notifications-body': 'Push notifications are enabled.',
      'security-keys:': 'Security devices:',
      'add-security-key': 'Register new security key',
      'add-passkey': 'Register new passkey',
      'enter-security-key-name': 'Enter a name for the security key',
      'added': 'Added on',
      'test': 'Test',
      'enter-otp': 'Enter your One-Time Passcode (OTP):',
      'otp-or-sk-required': 'MFA requires OTP or at least one security key',
      'remote-mfa-title': 'Approval Requested',
      'remote-mfa-body': 'An action on another device needs approval.',
      'approve': 'Approve 👍',
      'deny': 'Deny 🚫',
      'select-security-key': 'Select the security device to register',
      'verify-identity': 'Please verify your identity',
      'cover': 'Cover image:',
      'cover-selected': 'Selected image',
      'cover-latest': 'Most recent',
      'cover-blank': 'No image',
    },
    'fr': { // French translation generated by NotebookLM
      'LANG': 'Français',
      'language': 'Langue',
      'login': 'Connexion',
      'logging-in': 'Connexion en cours',
      'login-failed': 'Échec de la connexion',
      'register': 'S\'inscrire',
      'create-account': 'Créer un compte',
      'creating-account': 'Création de compte en cours',
      'create-account-failed': 'Échec de la création de compte',
      'recover': 'Récupérer',
      'recover-account': 'Récupérer le compte',
      'recovering-account': 'Récupération de compte en cours',
      'recover-account-failed': 'Échec de la récupération de compte',
      'enter-passphrase-text': '<p>Saisissez une phrase secrète pour chiffrer les données de votre application.</p>',
      'reenter-passphrase-text': '<p>Déverrouillez les données de votre application</p>',
      'set-passphrase': 'Confirmer',
      'setting-passphrase': 'Confirmation en cours',
      'skip-passphrase': 'Ignorer',
      'form-email': 'E-mail :',
      'form-password': 'Mot de passe :',
      'form-new-password': 'Nouveau mot de passe :',
      'form-confirm-password': 'Confirmer le mot de passe :',
      'form-backup-phrase': 'Phrase de sauvegarde :',
      'form-backup-keys?': 'Sauvegarder les clés ?',
      'form-server': 'Serveur :',
      'server-placeholder': 'https://votre-nom-de-serveur/',
      'show': 'Afficher',
      'hide': 'Masquer',
      'skip-passphrase-warning': '⚠️ Ignorer la phrase secrète est moins sécurisé. Évitez d\'utiliser cette option sur un ordinateur public ou partagé. Continuer ?',
      'no-key-backup-warning': '⚠️ Votre clé secrète N\'EST PAS sauvegardée. Vous aurez besoin d\'une phrase de sauvegarde lors de votre prochaine connexion.',
      'enter-backup-phrase': 'Saisissez la phrase de sauvegarde :',
      'account': '👤 ▼',
      'account-title': 'Menu du compte',
      'trash-title': 'Corbeille',
      'refresh-title': 'Actualiser',
      'B': '$1 o',
      'KiB': '$1 Kio',
      'MiB': '$1 Mio',
      'GiB': '$1 Gio',
      'TiB': '$1 Tio',
      'MB': 'Mo',
      'GB': 'Go',
      'TB': 'To',
      'gallery': 'Galerie',
      'trash': 'Corbeille',
      'confirm': 'Confirmer 👍',
      'cancel': 'Annuler 🚫',
      'canceled': 'Annulé',
      'cache-full': 'Cache plein',
      'data-saving-on': 'Économie de données activée sur l\'appareil',
      'no-wifi': 'En attente de Wi-Fi',
      'caching-disabled': 'Mise en cache désactivée',
      'ready': 'Prêt',
      'drop-received': 'Traitement des nouveaux fichiers',
      'upload:': 'Téléchargement : $1',
      'collection': 'Collection',
      'collection:': '$1',
      'collection-title': 'Collection $1',
      'file-title': 'Fichier $1',
      'list': '▤ ',
      'list-title': 'Afficher en liste',
      'grid': '▦',
      'grid-title': 'Afficher en grille',
      'settings-title': 'Paramètres de la collection',
      'filename': 'Nom de fichier',
      'filesize': 'Taille du fichier',
      'creation-time': 'Heure de création',
      'filetype': 'Type de fichier',
      'duration': 'Durée',
      'shared-with': 'Partagé avec $1',
      'empty': 'Vide',
      'name': 'Nom :',
      'name:': 'Nom : $1',
      'size:': 'Taille : $1',
      'remove': 'Supprimer',
      'thumbnail-progress': 'Préparation : $1',
      'status:': 'Statut : $1',
      'upload-progress': 'Téléchargement : $1',
      'download-progress': 'Mise en cache : $1',
      'add-button-title': 'Ajouter des éléments',
      'upload-files': 'Télécharger des fichiers',
      'upload': 'Télécharger',
      'uploading': 'Téléchargement en cours',
      'select-upload': 'Sélectionnez les fichiers à télécharger (ou glissez-déposez les fichiers n\'importe où) :',
      'profile': 'Profil',
      'required': 'Obligatoire',
      'optional': 'Facultatif',
      'enable-mfa?': 'Exiger la MFA ?',
      'enable-otp?': 'Activer l\'OTP ?',
      'enable-passkey?': 'Utiliser les clés résidentes\n(ex. passkeys) ?',
      'enter-code': 'Saisir le code',
      'updating': 'Application des modifications',
      'error': 'Erreur',
      'new-pass-doesnt-match': 'Le nouveau mot de passe ne correspond pas',
      'otp-code-required': 'Code OTP requis',
      'delete-warning': '<p>⚠️ Si vous supprimez votre compte, toutes vos données seront définitivement supprimées.</p>',
      'delete-account': 'Supprimer mon compte',
      'confirm-delete-account': '⚠️ Êtes-vous sûr de vouloir supprimer définitivement votre compte ?\nL\'opération est irréversible.\n\nSaisissez votre mot de passe :',
      'key-backup': 'Sauvegarde des clés',
      'enter-current-password': 'Saisissez le mot de passe de votre compte :',
      'key-backup-warning': '<p>⚠️ La phrase de sauvegarde est votre clé secrète <b>non chiffrée</b>.</p><p>C\'est l\'information la plus sensible de votre compte. Elle peut être utilisée pour récupérer votre compte et vos données si votre clé secrète n\'est pas sauvegardée sur le serveur, ou si vous oubliez votre mot de passe.</p><p>Elle peut également être utilisée pour <b>PRENDRE LE CONTRÔLE</b> de votre compte.</p><p>Elle DOIT être gardée secrète. Écrivez-la sur un morceau de papier et rangez-la dans un coffre-fort.</p>',
      'show-backup-phrase': 'Afficher la phrase de sauvegarde',
      'hide-backup-phrase': 'Masquer la phrase de sauvegarde',
      'checking-password': 'Vérification du mot de passe',
      'key-backup-warning2': '<p>Choisissez si vous souhaitez conserver une sauvegarde chiffrée de votre clé secrète sur le serveur.<p><p>Si vous ne conservez PAS de sauvegarde, vous devrez saisir votre phrase de sauvegarde chaque fois que vous vous connecterez à votre compte.</p>',
      'enabled': 'Activé',
      'disabled': 'Désactivé',
      'opt-keep-backup': 'Conserver une sauvegarde sur le serveur (RECOMMANDÉ)',
      'opt-dont-keep-backup': '⚠️ NE PAS conserver de sauvegarde sur le serveur',
      'prefs': 'Préférences',
      'choose-cache-pref': '<h1>Cache :</h1>',
      'opt-encrypted': 'Stocker les fichiers chiffrés dans un cache de navigateur local. Des collections entières peuvent également être mises en cache pour un accès hors ligne. Le cache est vidé lors de la déconnexion ou lorsqu\'une autre option est sélectionnée. (PAR DÉFAUT)',
      'opt-no-store': 'Désactiver la mise en cache. Tous les fichiers, y compris les miniatures, sont récupérés et déchiffrés chaque fois qu\'ils sont consultés. C\'est l\'option la plus lente.',
      'opt-private': '⚠️ Utiliser le cache du navigateur par défaut. Les fichiers déchiffrés sont stockés dans le cache du navigateur. C\'est l\'option la plus susceptible de divulguer des informations.',
      'prefetch-all-thumbnails': 'Mettre en cache toutes les miniatures :',
      'use-mobile': 'Précharger avec les données mobiles :',
      'max-cache-size': 'Taille maximale du cache (Mio) :',
      'cache-usage': 'Utilisation actuelle : $1 Mio',
      'choose-notifications-pref': '<h1>Notifications :</h1>',
      'opt-enable-notifications': 'Activer les notifications push pour les événements importants, comme lorsque des amis ajoutent du contenu à des collections partagées.',
      'saved': 'Enregistré',
      'admin-console': 'Console d\'administration',
      'email': 'E-mail',
      'locked': 'Verrouillé',
      'approved': 'Approuvé',
      'admin': 'Admin',
      'quota': 'Quota',
      'open': 'Ouvrir',
      'download-doc': 'Télécharger le document',
      'copy-selected': 'Copier les fichiers sélectionnés',
      'move-selected': 'Déplacer les fichiers sélectionnés',
      'edit': 'Modifier',
      'edit:': 'Modifier : $1',
      'select': 'Sélectionner',
      'unselect': 'Désélectionner',
      'unselect-all': 'Désélectionner tout',
      'move-to-trash': 'Déplacer vers la corbeille',
      'confirm-move-to-trash': 'Déplacer vers la corbeille ?',
      'move-to-gallery': 'Déplacer vers la galerie',
      'confirm-move-to-gallery': 'Déplacer vers la galerie ?',
      'delete-perm': 'Supprimer définitivement',
      'confirm-delete-perm': '⚠️ Supprimer définitivement ?',
      'use-as-cover': 'Utiliser comme couverture',
      'move-to-gallery-only': 'Doit être déplacé de la corbeille vers la galerie',
      'moved-one-file': '1 fichier déplacé',
      'moved-many-files': '$1 fichiers déplacés',
      'copied-one-file': '1 fichier copié',
      'copied-many-files': '$1 fichiers copiés',
      'deleted-one-file': '1 fichier supprimé',
      'deleted-many-files': '$1 fichiers supprimés',
      'confirm-leave': '⚠️ Êtes-vous sûr de vouloir quitter cette collection ?',
      'delete': 'Supprimer',
      'confirm-delete': '⚠️ Êtes-vous sûr de vouloir supprimer cette collection ?',
      'properties': 'Propriétés',
      'properties:': 'Propriétés : $1',
      'offline-off': 'Disponible hors ligne ☐',
      'offline-on': 'Disponible hors ligne ☑',
      'create-collection': 'Créer une collection',
      'new-collection': 'NOUVELLE COLLECTION',
      'apply-changes': 'Appliquer les modifications',
      'no-changes': 'Aucune modification',
      'shared': 'Partagé :',
      'yes': 'Oui',
      'no': 'Non',
      'next': 'Suivant',
      'previous': 'Précédent',
      'close': 'Fermer la fenêtre',
      'info': 'Afficher les informations',
      'expand': 'Afficher plus de détails',
      'permissions': 'Autorisations :',
      'perm-add': 'Ajouter',
      'perm-share': 'Partager',
      'perm-copy': 'Copier',
      'members': 'Membres :',
      'contact-email': 'E-mail de contact',
      'add-member': 'Ajouter',
      'none': 'Aucun',
      'lock': 'Verrouiller',
      'logout': 'Déconnexion',
      'data-updated': 'Données mises à jour',
      'network-error': 'Hors ligne ?',
      'filter': 'Filtrer',
      'notification-encrypted-title': 'Notifications ($1)',
      'notification-encrypted-body': 'Nouvelles notifications chiffrées en attente.',
      'new-user-title': 'Nouvel utilisateur : $1',
      'new-content-body': 'Nouveaux fichiers ajoutés.',
      'new-collection-body': 'Partagé avec vous.',
      'new-members-body': 'Nouveaux membres ont rejoint.',
      'push-notifications-title': 'Notifications push',
      'push-notifications-body': 'Les notifications push sont activées.',
      'security-keys:': 'Dispositifs de sécurité :',
      'add-security-key': 'Enregistrer une nouvelle clé de sécurité',
      'add-passkey': 'Enregistrer une nouvelle passkey',
      'enter-security-key-name': 'Saisissez un nom pour la clé de sécurité',
      'added': 'Ajouté le',
      'test': 'Tester',
      'enter-otp': 'Saisissez votre code d\'accès à usage unique (OTP) :',
      'otp-or-sk-required': 'La MFA nécessite un OTP ou au moins une clé de sécurité',
      'remote-mfa-title': 'Approbation demandée',
      'remote-mfa-body': 'Une action sur un autre appareil nécessite une approbation.',
      'approve': 'Approuver 👍',
      'deny': 'Refuser 🚫',
      'select-security-key': 'Sélectionnez le dispositif de sécurité à enregistrer',
      'verify-identity': 'Veuillez vérifier votre identité',
      'cover': 'Image de couverture :',
      'cover-selected': 'Image sélectionnée',
      'cover-latest': 'La plus récente',
      'cover-blank': 'Aucune image',
    },
    'es': { // Spanish translation generated by NotebookLM
      'LANG': 'Español',
      'language': 'Idioma',
      'login': 'Iniciar sesión',
      'logging-in': 'Iniciando sesión',
      'login-failed': 'Error al iniciar sesión',
      'register': 'Registrarse',
      'create-account': 'Crear cuenta',
      'creating-account': 'Creando cuenta',
      'create-account-failed': 'Error al crear la cuenta',
      'recover': 'Recuperar',
      'recover-account': 'Recuperar cuenta',
      'recovering-account': 'Recuperando cuenta',
      'recover-account-failed': 'Error al recuperar la cuenta',
      'enter-passphrase-text': '<p>Ingrese una frase de contraseña para cifrar los datos de su aplicación.</p>',
      'reenter-passphrase-text': '<p>Desbloquee los datos de su aplicación</p>',
      'set-passphrase': 'Confirmar',
      'setting-passphrase': 'Confirmando',
      'skip-passphrase': 'Omitir',
      'form-email': 'Correo electrónico:',
      'form-password': 'Contraseña:',
      'form-new-password': 'Nueva contraseña:',
      'form-confirm-password': 'Confirmar contraseña:',
      'form-backup-phrase': 'Frase de respaldo:',
      'form-backup-keys?': '¿Respaldar claves?',
      'form-server': 'Servidor:',
      'server-placeholder': 'https://su-nombre-de-servidor/',
      'show': 'Mostrar',
      'hide': 'Ocultar',
      'skip-passphrase-warning': '⚠️ Omitir la frase de contraseña es menos seguro. Evite usar esta opción en una computadora pública o compartida. ¿Continuar?',
      'no-key-backup-warning': '⚠️ Su clave secreta NO está respaldada. Necesitará una frase de respaldo la próxima vez que inicie sesión.',
      'enter-backup-phrase': 'Ingrese la frase de respaldo:',
      'account': '👤 ▼',
      'account-title': 'Menú de cuenta',
      'trash-title': 'Papelera',
      'refresh-title': 'Actualizar',
      'B': '$1 B',
      'KiB': '$1 KiB',
      'MiB': '$1 MiB',
      'GiB': '$1 GiB',
      'TiB': '$1 TiB',
      'MB': 'MB',
      'GB': 'GB',
      'TB': 'TB',
      'gallery': 'Galería',
      'trash': 'Papelera',
      'confirm': 'Confirmar 👍',
      'cancel': 'Cancelar 🚫',
      'canceled': 'Cancelado',
      'cache-full': 'Caché lleno',
      'data-saving-on': 'Ahorro de datos habilitado en el dispositivo',
      'no-wifi': 'Esperando wifi',
      'caching-disabled': 'Caché deshabilitado',
      'ready': 'Listo',
      'drop-received': 'Procesando nuevos archivos',
      'upload:': 'Carga: $1',
      'collection': 'Colección',
      'collection:': '$1',
      'collection-title': 'Colección $1',
      'file-title': 'Archivo $1',
      'list': '▤ ',
      'list-title': 'Mostrar como lista',
      'grid': '▦',
      'grid-title': 'Mostrar como cuadrícula',
      'settings-title': 'Configuración de la colección',
      'filename': 'Nombre',
      'filesize': 'Tamaño',
      'creation-time': 'Fecha de creación',
      'filetype': 'Tipo',
      'duration': 'Duración',
      'shared-with': 'Compartido con $1',
      'empty': 'Vacío',
      'name': 'Nombre:',
      'name:': 'Nombre: $1',
      'size:': 'Tamaño: $1',
      'remove': 'Eliminar',
      'thumbnail-progress': 'Preparando: $1',
      'status:': 'Estado: $1',
      'upload-progress': 'Carga: $1',
      'download-progress': 'Almacenamiento en caché: $1',
      'add-button-title': 'Añadir elementos',
      'upload-files': 'Subir archivos',
      'upload': 'Subir',
      'uploading': 'Subiendo',
      'select-upload': 'Seleccione los archivos a subir (o arrastre y suelte los archivos en cualquier lugar):',
      'profile': 'Perfil',
      'required': 'obligatorio',
      'optional': 'opcional',
      'enable-mfa?': '¿Requerir MFA?',
      'enable-otp?': '¿Habilitar OTP?',
      'enable-passkey?': '¿Usar claves de residente\n(ej. passkeys)?',
      'enter-code': 'Ingresar código',
      'updating': 'Aplicando cambios',
      'error': 'Error',
      'new-pass-doesnt-match': 'La nueva contraseña no coincide',
      'otp-code-required': 'Código OTP requerido',
      'delete-warning': '<p>⚠️ Si elimina su cuenta, todos sus datos serán eliminados permanentemente.</p>',
      'delete-account': 'Eliminar mi cuenta',
      'confirm-delete-account': '⚠️ ¿Está seguro de que desea eliminar permanentemente su cuenta?\nLa operación no es reversible.\n\nIngrese su contraseña:',
      'key-backup': 'Respaldo de clave',
      'enter-current-password': 'Ingrese la contraseña de su cuenta:',
      'key-backup-warning': '<p>⚠️ La frase de respaldo es su clave secreta <b>no cifrada</b>.</p><p>Es la información más sensible de su cuenta. Puede usarse para recuperar su cuenta y sus datos si su clave secreta no está respaldada en el servidor, o si olvida su contraseña.</p><p>También puede usarse para <b>TOMAR EL CONTROL</b> de su cuenta.</p><p>DEBE mantenerse en secreto. Escríbala en un trozo de papel y guárdela en una caja fuerte.</p>',
      'show-backup-phrase': 'Mostrar frase de respaldo',
      'hide-backup-phrase': 'Ocultar frase de respaldo',
      'checking-password': 'Verificando contraseña',
      'key-backup-warning2': '<p>Elija si desea mantener una copia de seguridad cifrada de su clave secreta en el servidor.<p><p>Si NO mantiene una copia de seguridad, deberá ingresar su frase de copia de seguridad cada vez que inicie sesión en su cuenta.</p>',
      'enabled': 'Habilitado',
      'disabled': 'Deshabilitado',
      'opt-keep-backup': 'Mantener una copia de seguridad en el servidor (RECOMENDADO)',
      'opt-dont-keep-backup': '⚠️ NO mantener una copia de seguridad en el servidor',
      'prefs': 'Preferencias',
      'choose-cache-pref': '<h1>Caché:</h1>',
      'opt-encrypted': 'Almacenar archivos cifrados en una caché del navegador local. Colecciones enteras también pueden ser almacenadas en caché para acceso sin conexión. La caché se borra al cerrar sesión o al seleccionar otra opción. (PREDETERMINADO)',
      'opt-no-store': 'Desactivar la caché. Todos los archivos, incluidas las miniaturas, se recuperan y descifran cada vez que se acceden. Esta es la opción más lenta.',
      'opt-private': '⚠️ Usar la caché predeterminada del navegador. Los archivos descifrados se almacenan en la caché del navegador. Esta es la opción con mayor probabilidad de filtrar información.',
      'prefetch-all-thumbnails': 'Caché de todas las miniaturas:',
      'use-mobile': 'Precargar usando datos móviles:',
      'max-cache-size': 'Tamaño máximo de caché (MiB):',
      'cache-usage': 'Uso actual: $1 MiB',
      'choose-notifications-pref': '<h1>Notificaciones:</h1>',
      'opt-enable-notifications': 'Habilitar notificaciones push para eventos importantes como cuando amigos añaden contenido a colecciones compartidas.',
      'saved': 'Guardado',
      'admin-console': 'Consola de administración',
      'email': 'Correo electrónico',
      'locked': 'Bloqueado',
      'approved': 'Aprobado',
      'admin': 'Admin',
      'quota': 'Cuota',
      'open': 'Abrir',
      'download-doc': 'Descargar documento',
      'copy-selected': 'Copiar archivos seleccionados',
      'move-selected': 'Mover archivos seleccionados',
      'edit': 'Editar',
      'edit:': 'Editar: $1',
      'select': 'Seleccionar',
      'unselect': 'Deseleccionar',
      'unselect-all': 'Deseleccionar todo',
      'move-to-trash': 'Mover a la papelera',
      'confirm-move-to-trash': '¿Mover a la papelera?',
      'move-to-gallery': 'Mover a la galería',
      'confirm-move-to-gallery': '¿Mover a la galería?',
      'delete-perm': 'Eliminar permanentemente',
      'confirm-delete-perm': '⚠️ ¿Eliminar permanentemente?',
      'use-as-cover': 'Usar como portada',
      'move-to-gallery-only': 'Debe moverse de la papelera a la galería',
      'moved-one-file': '1 archivo movido',
      'moved-many-files': '$1 archivos movidos',
      'copied-one-file': '1 archivo copiado',
      'copied-many-files': '$1 archivos copiados',
      'deleted-one-file': '1 archivo eliminado',
      'deleted-many-files': '$1 archivos eliminados',
      'confirm-leave': '⚠️ ¿Está seguro de que desea salir de esta colección?',
      'delete': 'Eliminar',
      'confirm-delete': '⚠️ ¿Está seguro de que desea eliminar esta colección?',
      'properties': 'Propiedades',
      'properties:': 'Propiedades: $1',
      'offline-off': 'Disponible sin conexión ☐',
      'offline-on': 'Disponible sin conexión ☑',
      'create-collection': 'Crear colección',
      'new-collection': 'NUEVA COLECCIÓN',
      'apply-changes': 'Aplicar cambios',
      'no-changes': 'Sin cambios',
      'shared': 'Compartido:',
      'yes': 'Sí',
      'no': 'No',
      'next': 'Siguiente',
      'previous': 'Anterior',
      'close': 'Cerrar ventana',
      'info': 'Mostrar información',
      'expand': 'Mostrar más detalles',
      'permissions': 'Permisos:',
      'perm-add': 'Añadir',
      'perm-share': 'Compartir',
      'perm-copy': 'Copiar',
      'members': 'Miembros:',
      'contact-email': 'Correo electrónico de contacto',
      'add-member': 'Añadir',
      'none': 'Ninguno',
      'lock': 'Bloquear',
      'logout': 'Cerrar sesión',
      'data-updated': 'Datos actualizados',
      'network-error': '¿Sin conexión?',
      'filter': 'Filtrar',
      'notification-encrypted-title': 'Notificaciones ($1)',
      'notification-encrypted-body': 'Nuevas notificaciones cifradas esperando.',
      'new-user-title': 'Nuevo usuario: $1',
      'new-content-body': 'Nuevos archivos añadidos.',
      'new-collection-body': 'Compartido contigo.',
      'new-members-body': 'Nuevos miembros se unieron.',
      'push-notifications-title': 'Notificaciones push',
      'push-notifications-body': 'Las notificaciones push están habilitadas.',
      'security-keys:': 'Dispositivos de seguridad:',
      'add-security-key': 'Registrar nueva clave de seguridad',
      'add-passkey': 'Registrar nueva passkey',
      'enter-security-key-name': 'Ingrese un nombre para la clave de seguridad',
      'added': 'Añadido el',
      'test': 'Probar',
      'enter-otp': 'Ingrese su código de un solo uso (OTP):',
      'otp-or-sk-required': 'MFA requiere OTP o al menos una clave de seguridad',
      'remote-mfa-title': 'Aprobación solicitada',
      'remote-mfa-body': 'Una acción en otro dispositivo necesita aprobación.',
      'approve': 'Aprobar 👍',
      'deny': 'Denegar 🚫',
      'select-security-key': 'Seleccione el dispositivo de seguridad a registrar',
      'verify-identity': 'Por favor, verifique su identidad',
      'cover': 'Imagen de portada:',
      'cover-selected': 'Imagen seleccionada',
      'cover-latest': 'Más reciente',
      'cover-blank': 'Sin imagen',
    },
  },
};

Lang.init();
